### ISSUE TITLE
Primitive Shapes - Parameters and Defaults

### ISSUE THREAD

**Issue by RobinMorritt** [SamuelTS/SketchUp-Parametric-Modeling-Plugin#1]
The **_Sphere_** shape **_Node_** in _Parametric Modeling Version 0.0.3_ does not contain a **_Control_** to change the **_Segments_**. The default value is 40 Segments. This means, for example, it takes one minute processing time to **_Subtract_** one default overlapping **_Sphere_** from another and the user has no control over this.

Also, since the Parametric Modeling Shapes are derived from the Trimble Shapes plugin, it would be more consistent as well as faster to use the same default parameters for both plugins, as follows.

_Shape - Change to Parametric Modeling Shape_
**Box** - No change.
**Prism** - Make vertical lines Visible, not Soft and Smooth.
**Cylinder** - Change default Height to 1. Change default Segments to 16.
**Pyramid** - No change.
**Cone** - Change default Height to 1. Change default Segments to 16. Change Cone lines to Soft and Smooth.
**Sphere** - Change Segments to 16. Include a Segments parameter control in Node.

Trimble Shapes are in the foreground. Parametric Modeling 0.0.3 Shapes are in the background.
![Screenshot 2021-04-03 020535](https://user-images.githubusercontent.com/80362097/113463965-245f7780-9421-11eb-8260-c482aa80727d.png)

**Comment by SamuelTallet** [comment]
Thanks for this detailed request. I'll process it as soon as possible.

**Comment by SamuelTallet** [comment]
@RobinMorritt Changes you've requested will be visible from 0.0.4 version of Parametric Modeling plugin.
